// This file is generated by a script and should not be modified directly.
const markdown: string =
  "**Un couple CFD-RNCP a une période de validité** qui correspond à l’intersection de la période d’ouverture du diplôme et de la période d’activité de la fiche RNCP.\n";
export default markdown;
