// This file is generated by a script and should not be modified directly.
const markdown: string =
  "To streamline your users' journey, this API allows you to directly transmit your users' applications to recruiters without them having to leave your site.\n\nFor this, it only requires the transmission of the candidate's contact information and resume. A cover letter, addressed to the recruiter, can also be optionally submitted. The application is then sent to the recruiter via email.\n";
export default markdown;
