// This file is generated by a script and should not be modified directly.
const markdown: string = "Department numbers specified in an array\n\nexample : [\"75\", \"77\", \"92\"]\n";
export default markdown