// This file is generated by a script and should not be modified directly.
const markdown: string =
  "Target diploma level at the end of studies.\n\nWhen filtering by diploma level, we return offers:\n\n- where the target diploma level is unknown / not specified / indifferent\n- **and** where the target diploma level matches the requested diploma level\n\nBy filtering on `4`, only offers related to this diploma level, as well as those with unknown/unspecified levels, will be returned to you.\n";
export default markdown;
