// This file is generated by a script and should not be modified directly.
const markdown: string =
  "La [Base Centrale des Nomenclatures](https://infocentre.pleiade.education.fr/bcn/) (BCN) est administrée par l’Éducation nationale.\n\nLe [Répertoire des Certifications Professionnelles](https://www.francecompetences.fr/recherche-resultats/?types=certification&search=&pageType=certification&active=1) (RNCP) est administré par France Compétences. **Il contient des fiches antérieures à la réforme de 2019 pour lesquelles certains champs étaient alors inexistants ou optionnels.**\n";
export default markdown;
