// This file is generated by a script and should not be modified directly.
const markdown: string =
  "La période de validité d’un CFD est décrite par :\n\n- **La date d’ouverture** : moment où il est possible de s’inscrire pour l’obtention de la certification (ou du diplôme).\n- **La première session** : année de sortie des premiers diplômés.\n- **La dernière session** : année de sortie des derniers diplômés.\n- **La date de fermeture** : moment où il n’est plus possible d’émettre le diplôme.\n";
export default markdown;
