// This file is generated by a script and should not be modified directly.
const markdown: string =
  "Groups elements that describe the field to which the company's SIRET number is linked:\n\nThe French Classification of Activities (NAF). Produced by INSEE, its aim is to facilitate the organization of economic and social information.\nThe IDCC number of the collective agreement. Produced by the ministry responsible for labor (Dares and DGT) and the one responsible for agriculture.\nThe Competency Operator (OPCO) responsible for managing the funding of the contract.\n";
export default markdown;
