// This file is generated by a script and should not be modified directly.
const markdown: string =
  "Postal address of the contract execution location. If provided, it must be as precise as possible as it is used to derive the GPS coordinates of the location, via the [Adresse API](https://www.data.gouv.fr/dataservices/api-adresse-base-adresse-nationale-ban). If no address is provided, the address and the geolocation of the offer are derived from the company’s SIRET.\n"
export default markdown
