export const expectedDocumentationDelta = {
  "get:/job/v1/search": [
    {
      path: ["parameters", "longitude", "schema", "type"],
      type: "CHANGE",
      value: ["number", "null"],
      oldValue: "number",
    },
    {
      path: ["parameters", "latitude", "schema", "type"],
      type: "CHANGE",
      value: ["number", "null"],
      oldValue: "number",
    },
    {
      path: ["parameters", "radius", "schema", "type"],
      type: "CHANGE",
      value: ["number", "null"],
      oldValue: "number",
    },
    {
      path: ["parameters", "romes", "schema", "type"],
      type: "CHANGE",
      value: ["string", "null"],
      oldValue: "string",
    },
    {
      path: ["parameters", "rncp", "schema", "type"],
      type: "CHANGE",
      value: ["string", "null"],
      oldValue: "string",
    },
    {
      path: [
        "responses",
        "200",
        "content",
        "application/json",
        "schema",
        "properties",
        "jobs",
        "items",
        "properties",
        "workplace",
        "properties",
        "domain",
        "properties",
        "opco",
        "enum",
      ],
      type: "CHANGE",
      value: [
        "AFDAS",
        "AKTO / Opco entreprises et salariés des services à forte intensité de main d'oeuvre",
        "ATLAS",
        "Constructys",
        "L'Opcommerce",
        "OCAPIAT",
        "OPCO 2i",
        "Opco entreprises de proximité",
        "Opco Mobilités",
        "Opco Santé",
        "Uniformation, l'Opco de la Cohésion sociale",
        "inconnu",
        "OPCO multiple",
      ],
    },
    {
      path: [
        "responses",
        "200",
        "content",
        "application/json",
        "schema",
        "properties",
        "recruiters",
        "items",
        "properties",
        "identifier",
        "properties",
        "id",
      ],
      type: "CHANGE",
      oldValue: {
        _: "schema",
        type: "string",
      },
    },
    {
      path: [
        "responses",
        "200",
        "content",
        "application/json",
        "schema",
        "properties",
        "recruiters",
        "items",
        "properties",
        "identifier",
        "required",
      ],
      type: "CHANGE",
      oldValue: ["id"],
    },
    {
      path: [
        "responses",
        "200",
        "content",
        "application/json",
        "schema",
        "properties",
        "recruiters",
        "items",
        "properties",
        "workplace",
        "properties",
        "domain",
        "properties",
        "opco",
        "enum",
      ],
      type: "CHANGE",
      value: [
        "AFDAS",
        "AKTO / Opco entreprises et salariés des services à forte intensité de main d'oeuvre",
        "ATLAS",
        "Constructys",
        "L'Opcommerce",
        "OCAPIAT",
        "OPCO 2i",
        "Opco entreprises de proximité",
        "Opco Mobilités",
        "Opco Santé",
        "Uniformation, l'Opco de la Cohésion sociale",
        "inconnu",
        "OPCO multiple",
      ],
    },
  ],
  "post:/job/v1/offer": [
    {
      path: [
        "requestBody",
        "content",
        "application/json",
        "schema",
        "properties",
        "contract",
        "properties",
        "type",
        "default",
      ],
      type: "CHANGE",
      value: ["Apprentissage", "Professionnalisation"],
    },
    {
      path: [
        "requestBody",
        "content",
        "application/json",
        "schema",
        "properties",
        "contract",
        "properties",
        "start",
        "default",
      ],
      type: "CHANGE",
      oldValue: ["Apprentissage", "Professionnalisation"],
    },
    {
      path: ["responses", "200", "content", "application/json", "schema", "properties", "id"],
      type: "CHANGE",
      oldValue: {
        _: "schema",
        type: "string",
      },
    },
    {
      path: ["responses", "200", "content", "application/json", "schema", "required"],
      type: "CHANGE",
      oldValue: ["id"],
    },
  ],
  "put:/job/v1/offer/{id}": [
    {
      path: ["parameters", "id", "required"],
      type: "CHANGE",
      value: false,
      oldValue: true,
    },
    {
      path: ["parameters", "id", "schema"],
      type: "CHANGE",
      oldValue: {
        _: "schema",
        type: "string",
      },
    },
    {
      path: [
        "requestBody",
        "content",
        "application/json",
        "schema",
        "properties",
        "contract",
        "properties",
        "type",
        "default",
      ],
      type: "CHANGE",
      value: ["Apprentissage", "Professionnalisation"],
    },
    {
      path: [
        "requestBody",
        "content",
        "application/json",
        "schema",
        "properties",
        "contract",
        "properties",
        "start",
        "default",
      ],
      type: "CHANGE",
      oldValue: ["Apprentissage", "Professionnalisation"],
    },
    {
      path: ["responses", "204", "content"],
      type: "CHANGE",
      value: {
        "application/json": {
          schema: {
            _: "schema",
            type: "null",
          },
        },
      },
    },
  ],
};
