// This file is generated by a script and should not be modified directly.
const markdown: string = "Filtrer les offres d’emploi par opco. voir la liste des valeurs possibles.\n";
export default markdown;
