// This file is generated by a script and should not be modified directly.
const markdown: string =
  "Niveau de diplôme cible à la fin des études.\n\nLors du filtrage par niveau de diplôme, nous retournons les données :\n\n- où le niveau de diplôme cible est inconnu / non précisé / indifférent\n- **et** lorsque le niveau de diplôme cible correspond au niveau de diplôme demandé\n\nEn filtrant sur le « 4 », seules les données relatives à ce niveau de diplôme, ainsi que celles avec des niveaux inconnus ou non précisés, vous seront renvoyées.\n";
export default markdown;
