// This file is generated by a script and should not be modified directly.
const markdown: string =
  "Un enregistrement au RNCP est de maximum 5 ans, dépassé ce délai toute fiche doit fait l’objet d’une demande de renouvellement.\n";
export default markdown;
