// This file is generated by a script and should not be modified directly.
const markdown: string = "Liste(s) de la ou des convention(s) collective(s) rattachées à la certification\n";
export default markdown