// This file is generated by a script and should not be modified directly.
const markdown: string =
  "Le type de certification renseigne sur\n\n- la nature du diplôme\n- le service responsable de la définition du diplôme\n- le(s) nom(s) et numéro(s) SIRET du ou des certificateur(s) renseigné(s) dans le RNCP\n- le type d’enregistrement au RNCP (de droit ou sur demande)\n- la voie d’accès à la formation (apprentissage, expérience, candidature individuelle, contrat de professionnalisation, formation continue et formation statut élève).\n";
export default markdown;
