// This file is generated by a script and should not be modified directly.
const markdown: string = "Liste du (ou des) code (s) et intitulé(s) des blocs de compétences validées par la certification\n";
export default markdown