// This file is generated by a script and should not be modified directly.
const markdown: string =
  "List of job offers corresponding to the search.\n\nThe offers come from:\n\n- collection on the platform La bonne alternance\n- France Travail\n- publication via API by our partners\n\nCurrently, the results are sorted by:\n\n- Source priority (La bonne alternance > France Travail > other partners)\n- Increasing distance (only for a search by location)\n- Decreasing date of creation\n\nThe results are limited to 150 per source, and currently, it is not possible to retrieve all the offers matching the search criteria.\n";
export default markdown;
