// This file is generated by a script and should not be modified directly.
const markdown: string =
  "List of warnings related to the search.\n\nFrance Travail job offers are retrieved in real-time, so in case of an error when calling the France Travail API, the France Travail offers will not be returned and a warning will be added to the response.\n";
export default markdown;
