// This file is generated by a script and should not be modified directly.
const markdown: string =
  "Cet élément regroupe les différents moyens de candidature proposés aux candidats.\n\n- URL vers laquelle rediriger le candidat pour qu’il postule\n- Numéro de téléphone de la personne chargée du recrutement\n- Email de la personne chargée du recrutement. Cet email ne sera pas visible par le candidat.\n- Identifiant de l’opportunité d’emploi à utiliser pour permettre à vos usagers de candidater directement depuis votre site grâce à [cette API complémentaire](./candidature-offre).\n";
export default markdown;
