// This file is generated by a script and should not be modified directly.
const markdown: string =
  "Regroupe des éléments qui décrivent le domaine auquel est rattaché le numéro SIRET de l’entreprise :\n\n- La Nomenclature d’Activité Française (NAF). Produite par l’INSEE, elle a pour objectif de faciliter l'organisation de l'information économique et sociale.\n- Le numéro IDCC de la convention collective. Produit par le ministère chargé du travail (Dares et DGT) et celui chargé de l’agriculture.\n- L’Opérateur de Compétence (OPCO) de rattachement pouvant prendre en charge le financement du contrat.\n";
export default markdown;
