// This file is generated by a script and should not be modified directly.
const markdown: string =
  "Adresse postale du lieu d’exécution du contrat. Si fournie, elle doit être la plus précise possible car elle est utilisée pour déduire les coordonnées GPS du lieu, via l’[API Adresse](https://www.data.gouv.fr/dataservices/api-adresse-base-adresse-nationale-ban). Si aucune adresse n’est fournie, l’adresse ainsi que la géolocalisation de l’offre sont déduites du SIRET de l’entreprise.\n"
export default markdown
