import nock from "nock";
import { describe, expect, it } from "vitest";

import { getKitApprentissageData } from "./kit_apprentissage.api.js";

describe("getKitApprentissageData", () => {
  it("should return the list data", async () => {
    const page1 = {
      data: [
        {
          cfd: "01022001",
          intitule_diplome: "AGENT DE CONTROLE NON DESTRUCTIF (MC NIVEAU IV)",
          rncp: "RNCP955",
          niv_fiche_RNCP: null,
          abrege_diplome: "CS",
          derniere_maj: "v1.3",
          acces_apprentissage: "Oui",
          date_echeance: "01/01/2025",
          etat_fiche: "INACTIVE",
          intitule_rncp: "CS - Agent de contrôle non destructif",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: null,
          date_limite_delivrance: null,
          nouvelle_certification: ["RNCP39682"],
          ancienne_certification: null,
        },
        {
          cfd: "01022103",
          intitule_diplome: "EMPLOYE TRAITEUR (MC NIVEAU III)",
          rncp: "RNCP37566",
          niv_fiche_RNCP: null,
          abrege_diplome: "CS",
          derniere_maj: "v1.0",
          acces_apprentissage: "Oui",
          date_echeance: "31/08/2026",
          etat_fiche: "ACTIVE",
          intitule_rncp: "CS - Employé traiteur",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2021",
          date_limite_delivrance: null,
          nouvelle_certification: null,
          ancienne_certification: ["RNCP958"],
        },
        {
          cfd: "01022104",
          intitule_diplome: "PATISSERIE, GLACERIE, CHOCOLATERIE, CONFISERIE SPECIALISEES (MC NIVEAU V)",
          rncp: "RNCP37316",
          niv_fiche_RNCP: null,
          abrege_diplome: "MC5",
          derniere_maj: "v2.9",
          acces_apprentissage: "Oui",
          date_echeance: "31/08/2024",
          etat_fiche: "INACTIVE",
          intitule_rncp: "MC5 - Pâtisserie, glacerie, chocolaterie, confiserie spécialisées",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2023",
          date_limite_delivrance: null,
          nouvelle_certification: ["RNCP38761"],
          ancienne_certification: ["RNCP6895"],
        },
        {
          cfd: "01022105",
          intitule_diplome: "CUISINIER EN DESSERTS DE RESTAURANT (MC NIVEAU III)",
          rncp: "RNCP37380",
          niv_fiche_RNCP: null,
          abrege_diplome: "CS",
          derniere_maj: "v1.0",
          acces_apprentissage: "Oui",
          date_echeance: "31/08/2026",
          etat_fiche: "ACTIVE",
          intitule_rncp: "CS - Cuisinier en desserts de restaurant",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2023",
          date_limite_delivrance: null,
          nouvelle_certification: null,
          ancienne_certification: ["RNCP6981"],
        },
        {
          cfd: "01022106",
          intitule_diplome: "VENDEUR SPECIALISE EN ALIMENTATION (MC NIVEAU III)",
          rncp: "RNCP37105",
          niv_fiche_RNCP: null,
          abrege_diplome: "CS",
          derniere_maj: "v2.9",
          acces_apprentissage: "Oui",
          date_echeance: "31/08/2028",
          etat_fiche: "ACTIVE",
          intitule_rncp: "CS - Vendeur-conseil en alimentation",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2023",
          date_limite_delivrance: null,
          nouvelle_certification: null,
          ancienne_certification: ["RNCP742"],
        },
        {
          cfd: "01022107",
          intitule_diplome: "BOULANGERIE SPECIALISEE (MC NIVEAU III)",
          rncp: "RNCP37313",
          niv_fiche_RNCP: null,
          abrege_diplome: "CS",
          derniere_maj: "v2.9",
          acces_apprentissage: "Oui",
          date_echeance: "31/08/2026",
          etat_fiche: "ACTIVE",
          intitule_rncp: "CS - Boulangerie spécialisée",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2023",
          date_limite_delivrance: null,
          nouvelle_certification: null,
          ancienne_certification: ["RNCP701"],
        },
        {
          cfd: "01022108",
          intitule_diplome: "PATISSERIE BOULANGERE (MC NIVEAU III)",
          rncp: "RNCP37315",
          niv_fiche_RNCP: null,
          abrege_diplome: "MC5",
          derniere_maj: "v2.9",
          acces_apprentissage: "Oui",
          date_echeance: "31/08/2024",
          etat_fiche: "INACTIVE",
          intitule_rncp: "MC5 - Pâtisserie boulangère",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2023",
          date_limite_delivrance: null,
          nouvelle_certification: ["RNCP38762"],
          ancienne_certification: ["RNCP2444"],
        },
        {
          cfd: "01022109",
          intitule_diplome: "ART DE LA CUISINE ALLEGEE (MC NIVEAU III)",
          rncp: "RNCP37567",
          niv_fiche_RNCP: null,
          abrege_diplome: "MC5",
          derniere_maj: "v1.0",
          acces_apprentissage: "Oui",
          date_echeance: "31/12/2024",
          etat_fiche: "INACTIVE",
          intitule_rncp: "MC5 - Art de la cuisine allégée",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2021",
          date_limite_delivrance: null,
          nouvelle_certification: null,
          ancienne_certification: ["RNCP4083"],
        },
        {
          cfd: "01022110",
          intitule_diplome: "PATISSERIE, GLACERIE, CHOCOLATERIE, CONFISERIE SPECIALISEES (MC NIVEAU III)",
          rncp: "RNCP37316",
          niv_fiche_RNCP: null,
          abrege_diplome: "MC5",
          derniere_maj: "v2.9",
          acces_apprentissage: "Oui",
          date_echeance: "31/08/2024",
          etat_fiche: "INACTIVE",
          intitule_rncp: "MC5 - Pâtisserie, glacerie, chocolaterie, confiserie spécialisées",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2023",
          date_limite_delivrance: null,
          nouvelle_certification: ["RNCP38761"],
          ancienne_certification: ["RNCP6895"],
        },
        {
          cfd: "01022111",
          intitule_diplome: "VENDEUR-CONSEIL EN ALIMENTATION (MC NIVEAU III)",
          rncp: "RNCP37105",
          niv_fiche_RNCP: null,
          abrege_diplome: "CS",
          derniere_maj: "CI-07122023",
          acces_apprentissage: "Oui",
          date_echeance: "31/08/2028",
          etat_fiche: "ACTIVE",
          intitule_rncp: "CS - Vendeur-conseil en alimentation",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2023",
          date_limite_delivrance: null,
          nouvelle_certification: null,
          ancienne_certification: ["RNCP742"],
        },
      ],
      total: 102,
      count: 10,
      pagination: {
        previous: null,
        next: "/get?page_num=2&page_size=10",
      },
    };

    const page2 = {
      data: [
        {
          cfd: "01022104",
          intitule_diplome: "PATISSERIE, GLACERIE, CHOCOLATERIE, CONFISERIE SPECIALISEES (MC NIVEAU V)",
          rncp: "RNCP37316",
          niv_fiche_RNCP: null,
          abrege_diplome: "MC5",
          derniere_maj: "v2.9",
          acces_apprentissage: "Oui",
          date_echeance: "31/08/2024",
          etat_fiche: "INACTIVE",
          intitule_rncp: "MC5 - Pâtisserie, glacerie, chocolaterie, confiserie spécialisées",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2023",
          date_limite_delivrance: null,
          nouvelle_certification: ["RNCP38761"],
          ancienne_certification: ["RNCP6895"],
        },
        {
          cfd: "01022105",
          intitule_diplome: "CUISINIER EN DESSERTS DE RESTAURANT (MC NIVEAU III)",
          rncp: "RNCP37380",
          niv_fiche_RNCP: null,
          abrege_diplome: "CS",
          derniere_maj: "v1.0",
          acces_apprentissage: "Oui",
          date_echeance: "31/08/2026",
          etat_fiche: "ACTIVE",
          intitule_rncp: "CS - Cuisinier en desserts de restaurant",
          type_enregistrement: "Enregistrement de droit",
          date_publication: null,
          date_decision: null,
          date_debut_parcours: "01/09/2023",
          date_limite_delivrance: null,
          nouvelle_certification: null,
          ancienne_certification: ["RNCP6981"],
        },
      ],
      total: 102,
      count: 2,
      pagination: {
        previous: "/get?page_num=1&page_size=2",
        next: "/get?page_num=3&page_size=2",
      },
    };

    const scope = nock("https://api-kit-apprentissage.intercariforef.org")
      .get("/cfd_rncp_intitule")
      .query({ page_num: 1, page_size: 100 })
      .matchHeader("token-connexion", "token-kit")
      .reply(200, page1);

    scope.get("/cfd_rncp_intitule").query({ page_num: 2, page_size: 100 }).reply(200, page2);

    const result = getKitApprentissageData();

    const data = [];
    for await (const item of result) {
      data.push(item);
    }

    expect(data).toEqual([
      ...page1.data.map(({ cfd, rncp }) => ({ cfd, rncp })),
      ...page2.data.map(({ cfd, rncp }) => ({ cfd, rncp })),
    ]);
  });
});
