// This file is generated by a script and should not be modified directly.
const markdown: string =
  "Liste des offres d’emploi correspondant à la recherche.\n\nLes offres proviennent de:\n\n- collection sur la plateforme La bonne alternance\n- France Travail\n- publication via API par nos partenaires\n- partenaire via flux spécifique.\n\nActuellement, les résultats sont triés par :\n\n- Priorité source (La bonne alternance > France Travail > autres partenaires)\n- Augmentation de la distance (uniquement pour une recherche par emplacement)\n- Date de création décroissante\n\nLes résultats sont limités à 150 par source, et actuellement, il n’est pas possible de récupérer toutes les offres correspondant aux critères de recherche.\n";
export default markdown;
