// This file is generated by a script and should not be modified directly.
const markdown: string = "Elements for submitting an application:\n\n- Redirect URL\n- Phone number\n- Company email\n";
export default markdown;
