// This file is generated by a script and should not be modified directly.
const markdown: string =
  "A contract is described by:\n\n- The type (apprenticeship and/or professionalization).\n- The start date.\n- The duration.\n- The work mode (on-site, remote, or hybrid).\n";
export default markdown;
