name: Update Documentation

on:
  pull_request:
    paths:
      - "sdk/src/docs/**/*.md"

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            .yarn/install-state.gz
            .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-

      - name: Install dependencies
        run: yarn install

      - name: Transpile markdown
        run: yarn workspace api-alternance-sdk markdown:transpile

      - name: Run Prettier
        run: yarn prettier:fix

      - name: typecheck
        run: yarn typecheck

      - name: Run Lint with fix
        run: yarn lint --fix

      - name: Commit changes if any
        run: |
          git config user.name "mna-devops[bot]"
          git config user.email "71841503+mna-devops@users.noreply.github.com"
          if git diff --quiet ./sdk/src/docs; then
            echo "No changes to commit"
            exit 0
          fi
          git add ./sdk/src/docs
          git commit -m "docs: update documentation" --no-verify
          git push
