on:
  release:
    types: [published]

jobs:
  tests:
    uses: "./.github/workflows/ci.yml"

  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            .yarn/install-state.gz
            .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-
          save-always: true

      - name: Install dependencies
        run: yarn install

      - name: Build & publish NPM release
        run: .bin/mna sdk:release "${{ github.event.release.tag_name }}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
