on:
  release:
    types: [published]

jobs:
  tests:
    uses: "./.github/workflows/ci.yml"

  release:
    needs: ["tests"]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          token: ${{ secrets.NPM_TOKEN }}
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            .yarn/install-state.gz
            .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-
          save-always: true

      - name: Install dependencies
        run: yarn install

      - name: Build & publish NPM release
        run: .bin/mna sdk:release "${{ github.event.release.tag_name }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Notify failure on Slack
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "La publication de la version ${{ github.event.release.tag_name }} a échoué"
          notify_when: "failure"
          mention_groups: "!channel"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify success on Slack
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "Version ${{ github.event.release.tag_name }} a été publiée avec succès"
          notify_when: "success"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
