// This file is generated by a script and should not be modified directly.
const markdown: string =
  "**Accédez gratuitement et en temps réel au détail d'une opportunité d'emploi en alternance.**\n\nL'utilisation de cette API est gratuite et réservée à des usages non lucratifs. Notez que toute utilisation de ces données à des fins commerciales, telles que la revente ou la facturation de l'accès pour des tiers comme des candidats, entreprises ou écoles, est interdite.\n";
export default markdown;
